security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
        App\Entity\User:
            algorithm: argon2i

    providers:
        chain_provider:
            chain:
                providers: [app_user_provider, in_memory]

        in_memory:
            memory:
                users:
                    admin@admin: { password: "111", roles: [ 'ROLE_ADMIN' ] }

        gate:
            memory:
                users:
                    '%gate_access_user%': { password: '%gate_access_psw%', roles: [ 'ROLE_GATE' ] }

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/shipping/address/data
            http_basic:
                provider: gate
            provider: gate

        main:
            logout:
                path:   app_logout
                handlers: [app.logout.listener]
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\AppMyAuthAuthenticator

    access_control:
        - { path: ^/api/shipping/address/data, role: ROLE_GATE }
        - { path: ^/index, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/doc, roles: [ROLE_USER, ROLE_ADMIN] }
