security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
        App\Entity\User:
            algorithm: argon2i

    providers:
        chain_provider:
            chain:
                providers: [app_user_provider, in_memory]

        in_memory:
            memory:
                users:
                    admin@admin: { password: "111", roles: [ 'ROLE_ADMIN' ] }

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout:
                path:   app_logout
                handlers: [app.logout.listener]
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - App\Security\AppMyAuthAuthenticator

    access_control:
        - { path: ^/index, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/doc, roles: [ROLE_USER, ROLE_ADMIN] }
