fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /doc

api_application:
  type: rest
  prefix:   /api
  resource: App\Controller\Api\ShippingAddress\ShippingAddressApiController
  options:
    expose: true