parameters:
    locale: 'en'
    app.logout_listener.class: App\Listener\LogoutListener
    doctrine.object.constructor.class: App\Serializer\Construction\DoctrineObjectConstructor
    app.object_manager.class: App\Service\ObjectManager
    app.shipping_address_object_manager.class: App\Service\ShippingAddressObjectManager
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.logout.listener:
        class: "%app.logout_listener.class%"
        arguments:
            - "@doctrine.orm.default_entity_manager"

    app_serialize.object_constructor:
      class: '%doctrine.object.constructor.class%'
      public: false
      arguments:
        - "@doctrine"
        - "@jms_serializer.unserialize_object_constructor"

    jms_serializer.object_constructor:
      public: false
      alias: app_serialize.object_constructor

    app.object_manager:
      abstract: true
      class: "%app.object_manager.class%"
      arguments:
        $serializer: "@jms_serializer"
        $validatorInterface: "@validator"
        $requestStack: "@request_stack"
        $tokenStorageInterface: "@security.token_storage"


    app.shipping_address_object_manager:
      parent: 'app.object_manager'
      class: "%app.shipping_address_object_manager.class%"
      autowire: true
      autoconfigure: false
      arguments:
        $shippingAddressRepository: '@App\Repository\ShippingAddressRepository'
